### PR TITLE
Update Test SDK to 16.1.1

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
I will squash when merging.

**Comment by onovotny** [comment]
Would this be 16.2.x by the time 3.0 ships? Not sure how these dependencies normally get tracked?

**Comment by livarcocc** [comment]
It is up to the VSTest team to decide if they need/will update their branding to match VS or not. They haven't done that yet. This is the latest they have pushed to the CLI so far.

**Comment by onovotny** [comment]
Is this getting merged? :)

**Pull request merged**
