### PR TITLE
Add nuget.client's feed URL

### PR DESCRIPTION
**Pull request by jcagme**
[NOMERGE!] Added feed is not created yet. 

Nuget client will start pushing their packages to "https://dotnetfeed.blob.core.windows.net/nuget-nugetclient" so in order to get the latest we need to add it to RestoreSources.

@dtivel 

skipciplease

### CODE REVIEW

**Comment by jcagme** [comment]
@livarcocc could you or someone in the repo PTAL so we can merge this?

**Comment by jcagme** [comment]
Adding more folks in hopes that someone will sign off

@dsplaisted @wli3 @pranavkm @nkolev92

**Comment by dsplaisted** [comment]
@jcagme The original description says "[NOMERGE!] Added feed is not created yet."  Is that feed created now?

**Comment by jcagme** [comment]
> @jcagme The original description says "[NOMERGE!] Added feed is not created yet." Is that feed created now?

True, yeah, forgot to remove that after all the checks passed after the feed was created.

Thanks!

**Pull request merged**
