### PR TITLE
First Pass dotnet/toolset repo: attempt 2

### PR DESCRIPTION
**Pull request by ghost**
First draft ToolSet build:

Download a pre-built CLI
Remove product compile
Remove SDK install scripts
Remove un-needed steps
Pare down the tests

Replaces: https://github.com/dotnet/toolset/pull/1
-the connection to my toolset fork was severed when I took the dotnet/toolset repo 'public'

### CODE REVIEW

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 Debug Build

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
test ci please

**Comment by tannergooding** [comment]
test this please

**Review by livarcocc — APPROVED** [review]

**Comment by tannergooding** [comment]
@livarcocc, could you review the new changes, now that everything is green.

**Comment by livarcocc** [comment]
LGTM.

**Pull request merged**
