### PR TITLE
Added a fake nupkg project to be published by this repo

### PR DESCRIPTION
**Pull request by livarcocc**
Added a fake nupkg project to be published by this repo to make it easier to do dependency uptake from it.

### CODE REVIEW

**Comment by mmitche** [comment]
Actually, should this be marked as non-shipping?

**Comment by livarcocc** [comment]
@mmitche you tell me!

**Comment by livarcocc** [comment]
Will DARC flow for the non-shipping package?

**Comment by mmitche** [comment]
@livarcocc Yeah, but we should mark it as non-shipping so we don't gather it for nuget.org release later on.

**Pull request merged**
