### PR TITLE
Insert NuGet Build 5.1.0-preview2.5965 into master

### PR DESCRIPTION
**Pull request by heng-liu**
Insert NuGet Build 5.1.0-preview2.5965 into toolset master

### CODE REVIEW

**Comment by heng-liu** [comment]
#3144

**Comment by heng-liu** [comment]
Insert NuGet Build 5.1.0-preview2.5965 into SDK master #3144

**Comment by heng-liu** [comment]
#3144

**Comment by heng-liu** [comment]
[#3144](https://github.com/dotnet/sdk/pull/3144)

**Comment by heng-liu** [comment]
Insert NuGet Build 5.1.0-preview2.5965 into SDK master  ##3144

**Comment by mmitche** [comment]
@heng-liu Is this needed for Preview 5?

**Comment by livarcocc** [comment]
We need a newer version for P6. Closing this one.

@heng-liu can you send us a new PR?

**Pull request closed without merging**
