### PR TITLE
Updating msbuild min version to 16.0.0

### PR DESCRIPTION
**Pull request by livarcocc**
This will effectively mean that the .NET Core SDK 3.0 will require VS 16.0 to work.

### CODE REVIEW

**Comment by livarcocc** [comment]
We have decided in shiproom to wait for Preview2 to put this change in. The plan is to make an announcement and provide guidance regarding this.

**Comment by IanKemp** [comment]
Why was this done? What is in 16.0 that is not in 15.9 and can/will not be backported? The issue is that this locks out everybody who uses VS2017.

**Comment by livarcocc** [comment]
There are lot of dependencies for the .NET Core SDK 3.0 on the latest VS tooling, more precisely, VS 16.3.

MSBuild is simply the one we use to force the SDK min-compat bar, but this is true for NuGet, Roslyn, FSharp and vstest console.

In the particular case of MSBuild, we added support to resx codegen for .net core in 16.3. For NuGet, we took dependencies on many new NuGet APIs to change how we represent the platform as we introduced Targeting packs and Runtime packs.

Making 3.0 require VS 16.3 is an explicit decision and it has been announced in our blob posts before.

**Comment by KathleenDollard** [comment]
@Iankemp 

Here is one of the places we've said that [.NET Core 3.0 is only supported in Visual Studio 2019 Update 16.3](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#prerequisites-for-net-core-30-preview-3)

**Pull request merged**
