### PR TITLE
Add the new Worker SDK

### PR DESCRIPTION
**Pull request by Tratcher**
This is a new SDK bundled with the web sdk.
@glennc

### CODE REVIEW

**Comment by vijayrkn** [comment]
@livarcocc @nguerrera - This is a new SDK. This gets built as part of websdk.

**Comment by vijayrkn** [comment]
@nguerrera - Do we need changes any where else for this to flow to cli? The latest preview4 build does not have this change.

**Comment by nguerrera** [comment]
For some reason the updates from toolset -> core-sdk (master) seem to be stalled. Toolset builds are green. @mmitche Ideas?

**Comment by nguerrera** [comment]
I forced it with `darc trigger-subscriptions --target-repo=core-sdk --source-repo=toolset --target-branch=master` and it's in progress: https://github.com/dotnet/core-sdk/pull/889

**Comment by mmitche** [comment]
@jcagme can you investigate why this didn't work before?

**Pull request merged**
