### PR TITLE
Updating CLI to 3.0.100-preview-20181103-1

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by peterhuene** [comment]
Given I was hoping to bump both the CLI and SDK with https://github.com/dotnet/cli/pull/10264, do we need this intermediate bump?

**Comment by peterhuene** [comment]
It's starting to look like it'll take a few more days to get the CLI passing with the latest SDK, so never mind :)

**Comment by peterhuene** [comment]
Now that I've merged the sdk bump, do we want to take that build instead?

**Comment by nguerrera** [comment]
Seems reasonable. I think that you also have to bump MicrosoftNETSdk version to match the build of dotnet/sdk you put in CLI. This is what I've been talking about with respect to conflicting sources of truth for MicrosoftNETSdk (dotnet/sdk). :(

**Comment by peterhuene** [comment]
`3.0.100-preview-20181105-1` and `3.0.100-preview.18554.1` are said versions.

**Comment by livarcocc** [comment]
Restore flakyness

@dotnet-bot Test Windows_NT x86 Debug Build

**Pull request merged**
